INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    2,
    'Eastbrook on the Greens',
    'We are a place to discover Welcome to Eastbrook on the Greens, redefining community design in Regina. Eastbrook combines carefully considered urban design and a unique sense of character wrapped up in a master-planned community built out by a select group of builder partners. This ensures the quality and experience provided to residents is unlike any other in the city.',
    '1,430 sqft',
    'Townhome',
    2,
    4,
    'https://assets.rew.ca/building-group/22128/images/Eastbrook_on_the_Greens_Elevation_Rendering_eastbrook_on_the_greens_02.jpg?auto=false&fit=crop&ixlib=react-8.5.1&h=644&w=1140',
    'Canada',
    'Regina',
    '5104 E Buckingham Dr',
    'Saskatchewan',
    'S4V 3A9',
    340000,
    'yes',
    'no',
    '2022-03-19'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    5,
    'Grandview East',
    'VIEW! VIEW! VIEW! Stunning Mountain and park view! TRULY A MAGNIFICENT QUALITY CUSTOM BUILT HOME in prestigious Quilchena area. Exterior & Interior uniquely designed by renowned Architect & Designer Loy Leyland. The backyard adjoins a huge open parkland! Both master and second bedroom overlook the huge green parkland and Northshore mountain. Modern kitchen is equipped with high-end cabinetry. stainless steel appliances and large center island. Supreme-finishing for intimate feeling of classic/modern living. Hardwood, Marble flooring. Top of the line applicances, high-end cabinetry, RADIANT FLOOR HEAT, A/C, HRV. Private and Scenery! Steps to well known PW secondary, Arbutus club, Arbutus mall. A pleasure to show!',
    '4,465 sqft',
    'Single House',
    5,
    6,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-vancouver-can/6c66b61355742caf9d5df7820d9a7dabc2042423-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Vancouver',
    '2185 W 32nd Avenue',
    'British Columbia',
    'V6L 2B1',
    650000,
    'yes',
    'yes',
    '2022-04-19'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    8,
    '4192 Columbia Street',
    'Nestled in a quiet tree-lined community, Nora is a curated collection of six townhomes that are thoughtfully designed from the inside out. Bespoke details and refined architecture pair with modern interiors that boast elevated finishes and a layout that invites moments of both peace and community. Every room in the home has intention and care at its heart. Warmth and ease surrounds the space, creating a townhouse that you can’t wait to come home to. Situated in the city’s beautiful West Side on an idyllic tree-lined corridor, nature abounds in this community. Braemar Park is steps from your front door, and both Queen Elizabeth and Van Dusen are just down the street. Book you private appointment today to come and learn more!',
    '1,088 sqft',
    'Townhome',
    3,
    3,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-vancouver-can/879dabbd5861ca0964780ce8ec96df8d0010ac7c-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Vancouver',
    '4192 Columbia Street',
    'British Columbia',
    'V5Y 2J6',
    250000,
    'yes',
    'yes',
    '2022-04-12'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    10,
    'Greater Sudbury',
    'Presenting this stunning custom built home, your opportunity to own the 2016 Kinsmen dream home! Unique home with an interesting layout with high ceilings and soaring windows with custom automatic blinds, bringing natural light in. Open concept main living areas that are perfect for entertaining and family living. Dream kitchen is light and bright with beautiful natural elements of wood and granite. Very thoughtful in design with a sprawling island that extends to a breakfast bar and a wall of built-in pantry cupboards. The family room has a modern gas fireplace that is highlighted by a stone backdrop that extends floor to ceiling.',
    '1,678 sqft',
    'Single House',
    3,
    4,
    'https://remax-listingphotos-ca1.imgix.net/x2/@v=-1412146182@/3176/2/250/2101250/2101250_1.jpg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Thunder Bay,',
    '20 Westport St',
    'Ontario',
    'P3B 0G2',
    898000,
    'yes',
    'yes',
    '2022-02-22'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    4,
    '1703 Victoria Ave E',
    'Enjoy the worry free benefits of condo living with this 1000 sq/ft meticulous 2 bedroom suite that includes secure entry, elevator access and indoor parking. Offering spacious living with this unit that has been well cared for and recently freshly painted. Featuring two spacious bedrooms, open concept dining and living area with patio doors that lead out to a balcony with views overlooking beautiful Lake of the Woods.',
    '1,020 sqft',
    'Condo',
    1,
    2,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-vancouver-can/3d10ae1d5525960055c031256d7a792830a01d9d-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&h=640',
    'Canada',
    'Kenora',
    '1703 Victoria Ave E',
    'Ontario',
    'S4V 3A9',
    265000,
    'yes',
    'no',
    '2022-04-24'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    7,
    '118-102 West Haven Drive',
    'Spacious 2-storey townhouse located in the gated community of Shannara Court - great starter home or investment property! Boasting FOUR BEDROOMS ABOVE GRADE! Walk-in to the main floor and the open concept floor plan including hickory hardwood floors, a large L-shaped kitchen, dining area, half bath and living room. The upper floor includes 4 bedrooms (1 without a closet) including a huge primary suite with 4pc ensuite and spacious walk-in closet.',
    '1,354 sqft',
    'Duplex',
    3,
    4,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-edmonton-can/685d96a08cf0a27b69c09045f4aea31fef7889e4-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Leduc',
    '118-102 West Haven Drive',
    'Alberta',
    'T9E 0A2',
    349000,
    'yes',
    'no',
    '2022-02-02'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    1,
    '5427 Allbright Square',
    'Welcome to well-maintained and better than new home with Walk Out Basement backing on lake in Allard. The 9’ height Main Floor has large Living Room with fireplace and feature wall, Gourmet Kitchen, Pantry, Dining and large deck. The kitchen has multiple counter space with Quartz Countertops, tiled back splash, servery/dry bar and Upgraded stainless steel Appliances. The upper floor has spacious Bonus Room, prayer room and 3 bedrooms.',
    '2,020 sqft',
    'Single House',
    3,
    3,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-edmonton-can/685d96a08cf0a27b69c09045f4aea31fef7889e4-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Edmonton,',
    '5427 Allbright Square',
    'Alberta',
    'T6W 3H6',
    380000,
    'yes',
    'no',
    '2022-04-07'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    1,
    '38 Serpentine St',
    'Backing onto a green belt in a family orientated neighbourhood in the Southlands area of St.John`s. This 2 storey home with a fully developed basement & 2076 square feet of space has 3 bedrooms, 3 1/2 baths, living room and kitchen/dining/great room across the back. The master has a 3 piece ensuite with shower and walk in closet. This lot is beautifully landscaped as seen in the photos, with paved 3 car driveway and vehicle access to the rear yard.',
    '2,076 sqft',
    'Single House',
    3,
    4,
    'https://remax-listingphotos-ca1.imgix.net/x2/@v=-644467053@/3155/5/587/1243587/1243587_1.jpg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Pasadena',
    '38 Serpentine St',
    'Nova Scotia',
    'A1H 0A8',
    359000,
    'yes',
    'yes',
    '2022-03-07'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    13,
    '9904 101 Avenue',
    'Come home to this exceptional townhouse with numerous upgrades located in Larose Terrace in Morinville. Close to schools, park and CFB Edmonton is just 20 minutes away. The lower main floor boasts a bright kitchen with large picture windows and a 12 ft ceiling, white cabinetry, travertine backsplash, granite countertops and stainless steel appliances and a convenient 2 piece bath. The main floor has a spacious open living room with a barnboard accent wall and dining room, perfect for entertaining. Both levels finished in ceramic tile and dark hardwood flooring. 2nd floor finds the primary bedroom with ensuite and walk in closet and 2 additional nice side bedrooms and the main bathroom, all finished in laminate flooring.',
    '1,278 sqft',
    'Single House',
    3,
    3,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-edmonton-can/bcb3deb5ebf924860c6e0967ac517fb6115f3e52-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Morinville',
    '9904 101 Avenue',
    'Alberta',
    'A1H 0A8',
    259000,
    'yes',
    'yes',
    '2022-04-07'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    14,
    '117-50 Heatherglen Drive',
    'Freedom 55! Live your best life in sought after, 55+, gated, adult living complex of Heritage Creek! Live active & independently in this showhome condition, 3 bedrooms + den, fully finished, stand alone house on a more private corner lot. House is beautifully upgraded w/new hardwood floors, tray ceiling w/ pot lights, extra wide staircase & solar sunblock film on west facing windows. Designer kitchen features a spacious island w/ granite counter tops, flat top stove, built in oven & microwave & SS fridge. Main floor laundry. Spa master ensuite w/infloor heating, soaker tub, stand alone shower, dual vanities & walk in closet.',
    '1,458 sqft',
    'Single House',
    3,
    3,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-edmonton-can/bcb3deb5ebf924860c6e0967ac517fb6115f3e52-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255https://remax-listingphotos-ca5.imgix.net/rets-images-edmonton-can/9c02e8bf496fe9e43ce0ebca3a5ccb33baf86b92-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Spruce Grove',
    '117-50 Heatherglen Drive',
    'Alberta',
    'T7X 0R6',
    349000,
    'yes',
    'no',
    '2022-04-26'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    14,
    '3119 Mcclocklin Road',
    'Beautiful 2 storey townhouse condo with single detached garage located in Hampton Village. Home offers 1,152 sq ft of living space with a fully finished basement. Mainfloor features large front living room, open concept kitchen and dining area and 2 piece bath. Bright and modern kitchen features tile backsplash and corner pantry. Second level offers 3 good sized bedrooms, 4 piece bath and laundry area with custom built-in cabinetry. Fully finished basement features family room, bedroom and 4 piece bath. Nice backyard is already set up for entertaining! Fully finished yard offers good sized deck, lower patio area with gazebo and outdoor turf. Single detached garage. Great location close to schools, parks and all amenities.',
    '1,458 sqft',
    'Duplex',
    3,
    4,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-saskatchewan-can/f7c3cc2b914da3b48fca5b6691b0a63f20b9674a-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Saskatoon',
    '3119 Mcclocklin Road',
    'Saskatchewan',
    'S7R 0J1',
    269000,
    'yes',
    'yes',
    '2022-04-22'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    14,
    '11609 Summit Crescent',
    'Impeccable house, located one of the most sought-after streets, Summit, in the beautiful, family-friendly & safe Sunshine Hills neighbourhood. This home was customized to reflect the original Westcoast Contemporary styling that sits on a 9000 sqft lot. A warm, bright, open layouts that invites refreshing sunlight into the house. Featuring 4 bedrooms upstairs & one on the main. Multiple exquisite renovations throughout including kitchen refresh (counters, backsplash, sink & appliances), gorgeous & durable wide-plank laminate flooring, all bathrooms replaced, newer furnace, pool resurfaced, and pump & heater replaced (2016). An upscale fully fenced sun-drenched backyard. Outdoor pool completes with kid-proof fences.',
    '2,858 sqft',
    'Single House',
    5,
    3,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-vancouver-can/720cf6c3e2b1f88a05add5ddc25afa3caf441463-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&h=640',
    'Canada',
    'Delta',
    '11609 Summit Crescent',
    'British Columbia',
    'V4E 2Z1',
    469000,
    'yes',
    'yes',
    '2022-03-29'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    3,
    '12018 237 Street',
    'Welcome to The Brooklands by Woodbridge Homes. Amazing one-bedroom Top floor unit on the quiet side of the building overlooking the courtyard with park Views! This home has a bright and open floorplan, stainless appliances, granite counters, in-suite laundry, laminate flooring, 10-foot ceilings, large windows, and a balcony. Great Clubhouse and amenities: Gym, Bike room, Media room and party room with full kitchen. Centrally located right next to shopping, TD Bank, Central City Shopping Mall.',
    '1,357 sqft',
    'Single House',
    3,
    3,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-vancouver-can/ed6976945998a94ac2f9b941faee20cd151e8c0b-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Maple Ridge',
    '12018 237 Street',
    'British Columbia',
    'V4R 2C8',
    269000,
    'yes',
    'yes',
    '2022-02-11'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    9,
    '1885 Loudoun Road',
    'Custom built executive home situated on 3 acres of landscaped land in desirable South Charleswood. This 2-storey home boasts 2493 sq ft of luxury finishes including solid hdwd flooring & doors throughout, wrought-iron railings, imported ceramic-tile, floor-to-ceiling tiled baths, granite counters in the kitchen & baths and a gourmet cherrywood kitchen w/ high end appliances. The primary bdrm offers a deluxe en-suite w/ over-sized jetted tub & Italian-tile surround, his/hers vanity, walk-in closet and a Juliet balcony overlooking the soaring 18ft great room!',
    '2,2549 sqft',
    'Single House',
    4,
    6,
    'https://remax-listingphotos-ca5.imgix.net/rets-images-winnipeg-can/6d6192540f782205309dc399c926087cb9a14b00-1-large.jpeg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Winnipeg',
    '12018 237 Street',
    'Manitoba',
    'V4R 2C8',
    559000,
    'yes',
    'yes',
    '2022-04-01'
  );
INSERT INTO properties (
    owner_id,
    title,
    description,
    area,
    property_type,
    number_of_bathrooms,
    number_of_bedrooms,
    image_url_1,
    country,
    city,
    street,
    province,
    post_code,
    price,
    active,
    featured,
    listing_date
  )
VALUES (
    4,
    '1585 South Park St',
    'Welcome to the Pavilion, one of the newest, prestigious condo communities. Strategically located in the heart of the city across from the Public Gardens and Citadel Hill and only 1 block off Spring Garden Rd. This 2 BR + Den will impress you. Lg southwest facing windows fill the condo with the warmth of natural light. This contemporary, open concept, condo has Bosch kitchen appliances; NG cooktop; cabinets by Wildwood all with Quartz countertop. The island was extended 27 providing plenty of additional work area and storage. The floor to ceiling marble surrounding the NG fireplace is impressive! Both BR have their own ensuite.',
    '2,2549 sqft',
    'Condo',
    2,
    3,
    'https://remax-listingphotos-ca1.imgix.net/x2/@v=-154420186@/63144/3/340/24271340/24271340_1.jpg?fit=max&auto=format,compress&fm=pjpg&cs=srgb&q=35&w=1255',
    'Canada',
    'Halifax',
    '1585 South Park St',
    'Nova Scotia',
    'B3J 0H8',
    239000,
    'yes',
    'yes',
    '2022-04-21'
  );
